# -*- coding: utf-8 -*-
"""20sw043(lab02).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qNsFL097xho6Ged-rAYaB8GNg1wJdhyB
"""

#Task 1

points = 16  # use this input to make your submission

# write your if statement here
if 1 <= points <= 50:
    result = "Congratulations! You won a wooden rabbit prize."
elif 51 <= points <= 150:
    result = "Congratulations! You won a no prize."
elif 151 <= points <= 180:
    result = "Congratulations! You won a water thin mint prize."
elif 181 <= points <= 200:
    result = "Congratulations! You won a penguin prize."
else:
    result = "Dear, no prize this time."

print(result)

#Task 2

answer = 42
guess = 25

if guess < answer:
    result = "Oops! Your guess was too low."
elif guess > answer:
    result = "Oops! Your guess was too high."
else:
    result = "Nice! Your guess matched the answer!"

print(result)

#Task 3

def calculate_tax(state, amount):
    # Dictionary to map states to their corresponding tax rates
    state_tax_rates = {
        'CA': 0.075,
        'MN': 0.095,
        'NY': 0.089,
    }

    # Check if the state exists in the dictionary
    if state in state_tax_rates:
        tax_rate = state_tax_rates[state]
        tax_amount = amount * tax_rate
        total_amount = amount + tax_amount
        return total_amount
    else:
        # If the state is not in the dictionary, return the original amount without tax
        return amount

# Taking input from the user
state = input("Enter your state (CA, MN, or NY): ")
amount = float(input("Enter the purchase amount: "))

# Calculate the total amount after applying tax
total_amount = calculate_tax(state, amount)

print(f"Total amount after tax: {total_amount:.2f}")

#Task 4

sentence = ["the", "quick", "brown", "fox", "jumped", "over", "the", "lazy", "dog"]

for word in sentence:
    print(word)

#Task 5

for number in range(5, 31, 5):
    print(number, end="\n")

#Task 6

names = ["Rick Sanchez", "Morty Smith", "Summer Smith", "Jerry Smith", "Beth Smith"]


first_names = [name.split()[0].lower() for name in names]

print(first_names)

#Task 7

multiples_3 = [num * 3 for num in range(1, 21)]

print(multiples_3)

#Task 8

scores = {
    "Rick Sanchez": 70,
    "Morty Smith": 35,
    "Summer Smith": 82,
    "Jerry Smith": 23,
    "Beth Smith": 98
}

passed = [name for name, score in scores.items() if score >= 65]

print(passed)

#Task 9

cast_names = ["Barney", "Robin", "Ted", "Lily", "Marshall"]
cast_heights = [72, 68, 72, 66, 76]

# Using zip() to create the 'cast' dictionary
cast = dict(zip(cast_names, cast_heights))

print(cast)

#Task 10

cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin", "Marshall Eriksen"]
heights = [72, 68, 72, 66, 76]

for i, name in enumerate(cast):
    cast[i] = name + str(heights[i])

print(cast)